### ISSUE TITLE
Custom species configuration doesn't save parameters

### ISSUE THREAD

**Issue by david81** [tphakala/birdnet-go#1200]
Attempting to add a custom species threshold results in no parameters being saved with the entry. The species name is saved, but no threshold or interval. This seems to allow some very low confidence detections to come through. 

Web UI after saving

<img width="1088" height="286" alt="Image" src="https://github.com/user-attachments/assets/28b5e6da-50af-4ae8-a9d9-2907941e4a1e" />

Web UI after refreshing

<img width="943" height="275" alt="Image" src="https://github.com/user-attachments/assets/1d66c9c5-0b70-4ff5-8935-ab1df8a047d6" />

**Comment by tphakala** [comment]
This is now fixed with https://github.com/tphakala/birdnet-go/pull/1201, thank you for reporting

**Comment by david81** [comment]
I'm still seeing the same behavior with nightly-20250825-1-g3b4f4c08. Support info generated and uploaded via the app.

**Comment by tphakala** [comment]
Could you try clearimg browser cache, and make sure to use new ui which is under /ui/ path

**Comment by david81** [comment]
Same result using a fresh browser (different machine) that hasn't accessed the app previously. I don't have an option to switch UI

<img width="996" height="525" alt="Image" src="https://github.com/user-attachments/assets/06c872c5-c1f6-44ee-af33-85bb536f0d4d" />

EDIT: sorry for misunderstanding the UI bit. I'd seen some previous screenshots that had a checkbox to switch the UI version. Oddly enough, navigating to the new UI Species page shows the values that were submitted but they are still missing in the current UI.

<img width="1211" height="187" alt="Image" src="https://github.com/user-attachments/assets/ad1ced0a-14c1-46a3-aabf-399c48dacdd8" />
