### ISSUE TITLE
Not uploading data to Birdweather

### ISSUE THREAD

**Issue by pack2010** [tphakala/birdnet-go#478]
Application has been working perfectly but then over last 12 hours am now getting this error message when trying to upload to Birdweather.

2025/02/19 08:12:59 Failed to decode JSON response: json: cannot unmarshal number into Go struct field .soundscape.duration of type string
2025/02/19 08:12:59 Failed to upload soundscape to Birdweather: json: cannot unmarshal number into Go struct field .soundscape.duration of type string
2025/02/19 08:12:59 error uploading to BirdWeather: json: cannot unmarshal number into Go struct field .soundscape.duration of type string
2025/02/19 08:12:59 Error executing action: json: cannot unmarshal number into Go struct field .soundscape.duration of type string

Is working fine to upload to the dashboard though.

Thanks!

**Comment by sclitheroe** [comment]
I have the same issue - running the latest DEV tagged docker image.

**Comment by tphakala** [comment]
This looks like a change on BirdWeather.com side, I'll provide a fix shortly.

**Comment by tphakala** [comment]
I believe this is now fixed by https://github.com/tphakala/birdnet-go/pull/479, new dev docker image should be ready in 15 minutes or so

**Comment by manicholls** [comment]
I pulled the latest dev down - 🐦 BirdNET-Go vunknown (built: 2025-02-19T14:53:19Z) but I'm still seeing the same failures around soundscape.duration.  I'm not sure if that's the correct build though.

**Comment by tphakala** [comment]
Yeah it seems that docker images don't have version string set correctly, I need to fix that at some point. @manicholls can you please provide error logs you are seeing?

**Comment by manicholls** [comment]
Here's the logs on debug.

`2025/02/19 12:29:54 Response Body: {"success":true,"soundscape":{"id":2075349522,"stationId":11028,"timestamp":"2025-02-19T12:29:41.000-05:00","url":"https://media.birdweather.com/soundscapes/5f7e2fad12425860ded10aec36b2f0e0","filesize":577580,"extension":"wav","duration":6.016,"mode":"birdnetpi"}}
2025/02/19 12:29:54 Failed to decode JSON response: json: cannot unmarshal number 6.016 into Go struct field .soundscape.duration of type int
2025/02/19 12:29:54 Failed to upload soundscape to Birdweather: failed to decode JSON response: json: cannot unmarshal number 6.016 into Go struct field .soundscape.duration of type int
2025/02/19 12:29:54 error uploading to BirdWeather: failed to upload soundscape to Birdweather: failed to decode JSON response: json: cannot unmarshal number 6.016 into Go struct field .soundscape.duration of type int
2025/02/19 12:29:54 Error executing action: failed to upload soundscape to Birdweather: failed to decode JSON response: json: cannot unmarshal number 6.016 into Go struct field .soundscape.duration of type int`

I'm not very familiar with GO but it seems like it needs to be float instead of an integer?

**Comment by tphakala** [comment]
@manicholls yes you are correct, type should be float, I set it to int based on BirdWeather API documentation .. I'll fix this.

**Comment by tphakala** [comment]
I tested latest fix and it seems to work at least for my nodes, I just released v0.6.2 with this fix included so I am closing this issue.
